language: julia
os:
  - linux
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: true
addons:
    apt_packages:
        - gfortran
cache:
  directories:
    - $HOME/.julia/v0.6/Ipopt
    - $HOME/.julia/v0.6/JuMP
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ ! -a "$HOME/.julia/v0.6/JuMP" ]]; julia -e 'Pkg.add("JuMP");'; fi
  - if [[ ! -a "$HOME/.julia/v0.6/Ipopt" ]]; julia -e 'Pkg.add("Ipopt"); Pkg.build("Ipopt");'; fi
  - julia --check-bounds=yes --depwarn=no -e 'Pkg.update(); Pkg.clone(pwd()); Pkg.build("DICE"); Pkg.test("DICE"; coverage=true)'
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("DICE")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("DICE")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
