site_name:        DICE.jl
repo_url:         https://github.com/Libbum/DICE.jl
site_description: A collection of open source DICE and DICE-like models
site_author:      Tim DuBois

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - API: api.md
